version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:17"
      timezone: "Europe/Berlin"
    groups:
      terraform-all:
        patterns:
          - "*"
    labels:
      - "dependabot"
      - "terraform"
    commit-message:
      prefix: "chore"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:17"
      timezone: "Europe/Berlin"
    groups:
      actions-all:
        patterns:
          - "*"
    labels:
      - "dependabot"
      - "github-actions"
    commit-message:
      prefix: "chore"